# Generated by Django 5.1.1 on 2024-10-16 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_campaign_landing_page_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landinggroup',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landing_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
