# Generated by Django 5.1.1 on 2024-10-07 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_campaignresult_link_clicked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='zip_file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
