# Generated by Django 5.1.1 on 2024-10-03 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_campaignresult_link_clicked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignresult',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaignresult',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaignresult',
            name='post_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
