# Generated by Django 5.1.1 on 2024-09-27 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_name_target_first_name_target_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignresult',
            name='token',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
