# Generated by Django 5.1.1 on 2024-10-03 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_campaignresult_latitude_campaignresult_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignresult',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
