# Generated by Django 5.1.1 on 2024-10-07 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_landingpage_zip_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='landing_pages', to='core.group'),
            preserve_default=False,
        ),
    ]
