# Generated by Django 5.1.1 on 2024-09-27 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_campaignresult_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignresult',
            name='click_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaignresult',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaignresult',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
    ]
