# Generated by Django 5.1.1 on 2024-10-07 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_campaignresult_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignresult',
            name='post_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
