# Generated by Django 5.1.1 on 2024-09-27 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_campaignresult_click_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignresult',
            name='email_opened_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaignresult',
            name='email_sent_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaignresult',
            name='landing_page_opened_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
