# Generated by Django 5.1.1 on 2024-10-01 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_campaignresult_email_opened_timestamp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaignresult',
            name='email_opened_timestamp',
        ),
        migrations.RemoveField(
            model_name='campaignresult',
            name='email_sent_timestamp',
        ),
        migrations.RemoveField(
            model_name='campaignresult',
            name='landing_page_opened_timestamp',
        ),
        migrations.AlterField(
            model_name='target',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='target',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='target',
            name='position',
            field=models.CharField(max_length=100),
        ),
    ]
