# Generated by Django 5.1.1 on 2024-10-07 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_landingpage_group_landinggroup_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='group',
        ),
        migrations.AddField(
            model_name='campaign',
            name='landing_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.landinggroup'),
            preserve_default=False,
        ),
    ]
