# Generated by Django 5.1.1 on 2024-10-07 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_campaign_group_campaign_landing_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='landing_page',
        ),
    ]
