# Generated by Django 5.1.1 on 2024-10-07 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_campaign_landing_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.group'),
            preserve_default=False,
        ),
    ]
