# Generated by Django 5.1.1 on 2024-10-17 10:28

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_landingpage_html_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingpage',
            name='html_content',
            field=tinymce.models.HTMLField(),
        ),
    ]
