# Generated by Django 5.1.1 on 2024-10-07 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_campaign_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignresult',
            name='landing_page',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.landingpage'),
            preserve_default=False,
        ),
    ]
