# Generated by Django 5.1.1 on 2024-10-07 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_campaignresult_landing_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaignresult',
            name='landing_page',
        ),
    ]
