# Generated by Django 5.1.1 on 2024-10-18 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_webhook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhook',
            name='secret',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
