# Generated by Django 5.1.1 on 2024-10-10 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_campaignresult_landing_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPageAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('landing_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='core.landingpage')),
            ],
        ),
    ]
