# Generated by Django 5.1.1 on 2024-10-10 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_landingpageasset'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='image_file_paths',
            field=models.TextField(default='[]'),
        ),
    ]
