# Generated by Django 5.1.1 on 2024-10-18 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_webhook_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignresult',
            name='webhook_sent',
            field=models.BooleanField(default=False),
        ),
    ]
