# Generated by Django 5.1.1 on 2024-10-10 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_landingpage_image_file_paths'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpageasset',
            name='relative_path',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='landingpageasset',
            name='file_type',
            field=models.CharField(max_length=10),
        ),
    ]
